import type { Akun } from '@/types'

export const mockAkun: Akun[] = [
  // ===== ASET (1xxx) =====
  {
    id: 'akun-1000',
    code: '1000',
    name: 'ASET',
    type: 'asset',
    normalBalance: 'debit',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-1100',
    code: '1100',
    name: 'Aset Lancar',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1000',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-1101',
    code: '1101',
    name: 'Kas Sekolah',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 45250000,
  },
  {
    id: 'akun-1102',
    code: '1102',
    name: 'Bank BCA',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 285000000,
  },
  {
    id: 'akun-1103',
    code: '1103',
    name: 'Bank BSI',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 142500000,
  },
  {
    id: 'akun-1104',
    code: '1104',
    name: 'Piutang SPP',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 38750000,
  },
  {
    id: 'akun-1105',
    code: '1105',
    name: 'Piutang Lain-lain',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 5000000,
  },
  {
    id: 'akun-1106',
    code: '1106',
    name: 'Perlengkapan Sekolah',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1100',
    isActive: true,
    balance: 12000000,
  },
  {
    id: 'akun-1200',
    code: '1200',
    name: 'Aset Tetap',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1000',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-1201',
    code: '1201',
    name: 'Tanah',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1200',
    isActive: true,
    balance: 2500000000,
  },
  {
    id: 'akun-1202',
    code: '1202',
    name: 'Bangunan',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1200',
    isActive: true,
    balance: 1850000000,
  },
  {
    id: 'akun-1203',
    code: '1203',
    name: 'Peralatan dan Mesin',
    type: 'asset',
    normalBalance: 'debit',
    parentId: 'akun-1200',
    isActive: true,
    balance: 385000000,
  },
  {
    id: 'akun-1204',
    code: '1204',
    name: 'Akumulasi Penyusutan Bangunan',
    type: 'asset',
    normalBalance: 'credit',
    parentId: 'akun-1200',
    isActive: true,
    balance: -245000000,
  },
  {
    id: 'akun-1205',
    code: '1205',
    name: 'Akumulasi Penyusutan Peralatan',
    type: 'asset',
    normalBalance: 'credit',
    parentId: 'akun-1200',
    isActive: true,
    balance: -125000000,
  },

  // ===== LIABILITAS (2xxx) =====
  {
    id: 'akun-2000',
    code: '2000',
    name: 'LIABILITAS',
    type: 'liability',
    normalBalance: 'credit',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-2101',
    code: '2101',
    name: 'Hutang Usaha',
    type: 'liability',
    normalBalance: 'credit',
    parentId: 'akun-2000',
    isActive: true,
    balance: 65800000,
  },
  {
    id: 'akun-2102',
    code: '2102',
    name: 'Simpanan Siswa',
    type: 'liability',
    normalBalance: 'credit',
    parentId: 'akun-2000',
    isActive: true,
    balance: 8350000,
  },
  {
    id: 'akun-2103',
    code: '2103',
    name: 'Titipan SPP',
    type: 'liability',
    normalBalance: 'credit',
    parentId: 'akun-2000',
    isActive: true,
    balance: 4500000,
  },
  {
    id: 'akun-2104',
    code: '2104',
    name: 'Hutang Pajak (PPh 21)',
    type: 'liability',
    normalBalance: 'credit',
    parentId: 'akun-2000',
    isActive: true,
    balance: 3200000,
  },
  {
    id: 'akun-2105',
    code: '2105',
    name: 'Hutang BPJS',
    type: 'liability',
    normalBalance: 'credit',
    parentId: 'akun-2000',
    isActive: true,
    balance: 5850000,
  },

  // ===== EKUITAS (3xxx) =====
  {
    id: 'akun-3000',
    code: '3000',
    name: 'EKUITAS',
    type: 'equity',
    normalBalance: 'credit',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-3101',
    code: '3101',
    name: 'Modal Yayasan',
    type: 'equity',
    normalBalance: 'credit',
    parentId: 'akun-3000',
    isActive: true,
    balance: 4174300000,
  },
  {
    id: 'akun-3102',
    code: '3102',
    name: 'Surplus Ditahan',
    type: 'equity',
    normalBalance: 'credit',
    parentId: 'akun-3000',
    isActive: true,
    balance: 285000000,
  },
  {
    id: 'akun-3103',
    code: '3103',
    name: 'Surplus/Defisit Tahun Berjalan',
    type: 'equity',
    normalBalance: 'credit',
    parentId: 'akun-3000',
    isActive: true,
    balance: 0,
  },

  // ===== PENDAPATAN (4xxx) =====
  {
    id: 'akun-4000',
    code: '4000',
    name: 'PENDAPATAN',
    type: 'revenue',
    normalBalance: 'credit',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-4101',
    code: '4101',
    name: 'Pendapatan SPP',
    type: 'revenue',
    normalBalance: 'credit',
    parentId: 'akun-4000',
    isActive: true,
    balance: 875000000,
  },
  {
    id: 'akun-4102',
    code: '4102',
    name: 'Pendapatan Kegiatan Siswa',
    type: 'revenue',
    normalBalance: 'credit',
    parentId: 'akun-4000',
    isActive: true,
    balance: 125000000,
  },
  {
    id: 'akun-4103',
    code: '4103',
    name: 'Pendapatan Dana BOS',
    type: 'revenue',
    normalBalance: 'credit',
    parentId: 'akun-4000',
    isActive: true,
    balance: 350000000,
  },
  {
    id: 'akun-4104',
    code: '4104',
    name: 'Pendapatan Lain-lain',
    type: 'revenue',
    normalBalance: 'credit',
    parentId: 'akun-4000',
    isActive: true,
    balance: 18500000,
  },

  // ===== BEBAN (5xxx) =====
  {
    id: 'akun-5000',
    code: '5000',
    name: 'BEBAN',
    type: 'expense',
    normalBalance: 'debit',
    isActive: true,
    balance: 0,
  },
  {
    id: 'akun-5101',
    code: '5101',
    name: 'Biaya Gaji dan Tunjangan',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 682000000,
  },
  {
    id: 'akun-5102',
    code: '5102',
    name: 'Biaya BPJS Ketenagakerjaan',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 48500000,
  },
  {
    id: 'akun-5103',
    code: '5103',
    name: 'Biaya Operasional Sekolah',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 95000000,
  },
  {
    id: 'akun-5104',
    code: '5104',
    name: 'Biaya Penyusutan Aset Tetap',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 38500000,
  },
  {
    id: 'akun-5105',
    code: '5105',
    name: 'Biaya Kegiatan Siswa',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 85000000,
  },
  {
    id: 'akun-5106',
    code: '5106',
    name: 'Biaya Pemeliharaan Gedung',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 28000000,
  },
  {
    id: 'akun-5107',
    code: '5107',
    name: 'Biaya Listrik, Air, dan Internet',
    type: 'expense',
    normalBalance: 'debit',
    parentId: 'akun-5000',
    isActive: true,
    balance: 45000000,
  },
]
