import type { Asset } from '@/types'

export const mockAssets: Asset[] = [
  {
    id: 'aset-1',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    assetCode: 'SD-KMP-001',
    name: 'Laptop Dell Inspiron 15',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2023-01-15',
    acquisitionCost: 9500000,
    residualValue: 950000,
    usefulLifeMonths: 48,
    depreciationMethod: 'straight_line',
    bookValue: 5206250,
    status: 'active',
  },
  {
    id: 'aset-2',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    assetCode: 'SD-PRJ-001',
    name: 'Proyektor Epson EB-X41',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2022-07-20',
    acquisitionCost: 5800000,
    residualValue: 580000,
    usefulLifeMonths: 60,
    depreciationMethod: 'straight_line',
    bookValue: 3016667,
    status: 'active',
  },
  {
    id: 'aset-3',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    assetCode: 'SD-FRN-001',
    name: 'Meja Belajar Siswa (Set 30 Unit)',
    category: 'Furnitur',
    acquisitionDate: '2020-06-01',
    acquisitionCost: 18000000,
    residualValue: 1800000,
    usefulLifeMonths: 120,
    depreciationMethod: 'straight_line',
    bookValue: 10800000,
    status: 'active',
  },
  {
    id: 'aset-4',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    assetCode: 'SMP-AC-001',
    name: 'AC Split Daikin 1.5 PK (Lab Komputer)',
    category: 'Peralatan Gedung',
    acquisitionDate: '2021-09-10',
    acquisitionCost: 7500000,
    residualValue: 750000,
    usefulLifeMonths: 84,
    depreciationMethod: 'straight_line',
    bookValue: 4553571,
    status: 'active',
  },
  {
    id: 'aset-5',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    assetCode: 'SMP-KMP-001',
    name: 'Komputer Desktop Asus (10 Unit)',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2021-01-20',
    acquisitionCost: 45000000,
    residualValue: 4500000,
    usefulLifeMonths: 48,
    depreciationMethod: 'straight_line',
    bookValue: 16875000,
    status: 'active',
  },
  {
    id: 'aset-6',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    assetCode: 'SMP-GDG-001',
    name: 'Gedung Kelas Lantai 2 (4 Ruang)',
    category: 'Bangunan',
    acquisitionDate: '2018-08-01',
    acquisitionCost: 850000000,
    residualValue: 85000000,
    usefulLifeMonths: 240,
    depreciationMethod: 'straight_line',
    bookValue: 622187500,
    status: 'active',
  },
  {
    id: 'aset-7',
    schoolId: 'school-3',
    schoolName: 'SMA Al-Hikmah',
    assetCode: 'SMA-LAB-001',
    name: 'Peralatan Lab IPA (Set Lengkap)',
    category: 'Peralatan Lab',
    acquisitionDate: '2022-02-14',
    acquisitionCost: 65000000,
    residualValue: 6500000,
    usefulLifeMonths: 60,
    depreciationMethod: 'straight_line',
    bookValue: 43416667,
    status: 'active',
  },
  {
    id: 'aset-8',
    schoolId: 'school-3',
    schoolName: 'SMA Al-Hikmah',
    assetCode: 'SMA-KMP-001',
    name: 'Laptop Lenovo ThinkPad (5 Unit)',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2023-06-01',
    acquisitionCost: 42500000,
    residualValue: 4250000,
    usefulLifeMonths: 48,
    depreciationMethod: 'declining_balance',
    bookValue: 28916250,
    status: 'active',
  },
  {
    id: 'aset-9',
    schoolId: 'school-4',
    schoolName: 'SMK Al-Hikmah',
    assetCode: 'SMK-KMP-001',
    name: 'PC Rakitan Lab TKJ (20 Unit)',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2022-10-01',
    acquisitionCost: 80000000,
    residualValue: 8000000,
    usefulLifeMonths: 48,
    depreciationMethod: 'straight_line',
    bookValue: 47500000,
    status: 'active',
  },
  {
    id: 'aset-10',
    schoolId: 'school-4',
    schoolName: 'SMK Al-Hikmah',
    assetCode: 'SMK-SWT-001',
    name: 'Cisco Switch Catalyst 2960 (3 Unit)',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2022-10-01',
    acquisitionCost: 18000000,
    residualValue: 1800000,
    usefulLifeMonths: 60,
    depreciationMethod: 'straight_line',
    bookValue: 11520000,
    status: 'active',
  },
  {
    id: 'aset-11',
    schoolId: 'school-5',
    schoolName: 'MTs Al-Hikmah',
    assetCode: 'MTS-FRN-001',
    name: 'Kursi Siswa (Set 120 Unit)',
    category: 'Furnitur',
    acquisitionDate: '2019-07-15',
    acquisitionCost: 24000000,
    residualValue: 2400000,
    usefulLifeMonths: 120,
    depreciationMethod: 'straight_line',
    bookValue: 12600000,
    status: 'active',
  },
  {
    id: 'aset-12',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    assetCode: 'SD-PRN-001',
    name: 'Printer Canon iX6870',
    category: 'Peralatan Teknologi',
    acquisitionDate: '2020-03-10',
    acquisitionCost: 2800000,
    residualValue: 280000,
    usefulLifeMonths: 36,
    depreciationMethod: 'straight_line',
    bookValue: 0,
    status: 'disposed',
  },
]
