import type { CashTransaction } from '@/types'

export const mockCashTransactions: CashTransaction[] = [
  {
    id: 'kas-1',
    schoolId: 'school-1',
    type: 'receipt',
    date: '2026-06-05',
    amount: 3850000,
    category: 'Penerimaan SPP',
    description: 'Rekap penerimaan SPP SD Al-Hikmah Juni 2026 batch 1',
    status: 'posted',
    referenceNumber: 'KAS-SD-2026-0601',
    createdBy: 'Budi Santoso',
  },
  {
    id: 'kas-2',
    schoolId: 'school-1',
    type: 'payment',
    date: '2026-06-06',
    amount: 1500000,
    category: 'Pembelian ATK',
    description: 'Pembelian alat tulis kantor untuk kebutuhan semester genap',
    status: 'posted',
    referenceNumber: 'KAS-SD-2026-0602',
    createdBy: 'Budi Santoso',
  },
  {
    id: 'kas-3',
    schoolId: 'school-1',
    type: 'payment',
    date: '2026-06-08',
    amount: 750000,
    category: 'Biaya Kebersihan',
    description: 'Pembayaran jasa kebersihan bulan Juni 2026',
    status: 'posted',
    referenceNumber: 'KAS-SD-2026-0603',
    createdBy: 'Budi Santoso',
  },
  {
    id: 'kas-4',
    schoolId: 'school-2',
    type: 'receipt',
    date: '2026-06-04',
    amount: 5250000,
    category: 'Penerimaan SPP',
    description: 'Rekap penerimaan SPP SMP Al-Hikmah Juni 2026',
    status: 'posted',
    referenceNumber: 'KAS-SMP-2026-0601',
    createdBy: 'Dewi Kurniasih',
  },
  {
    id: 'kas-5',
    schoolId: 'school-2',
    type: 'payment',
    date: '2026-06-10',
    amount: 2000000,
    category: 'Biaya Listrik',
    description: 'Pembayaran tagihan PLN bulan Mei 2026',
    status: 'posted',
    referenceNumber: 'KAS-SMP-2026-0602',
    createdBy: 'Dewi Kurniasih',
  },
  {
    id: 'kas-6',
    schoolId: 'school-3',
    type: 'receipt',
    date: '2026-06-07',
    amount: 6300000,
    category: 'Penerimaan SPP',
    description: 'Rekap penerimaan SPP SMA Al-Hikmah Juni 2026',
    status: 'posted',
    referenceNumber: 'KAS-SMA-2026-0601',
    createdBy: 'Rizki Pratama',
  },
  {
    id: 'kas-7',
    schoolId: 'school-3',
    type: 'payment',
    date: '2026-06-12',
    amount: 3500000,
    category: 'Biaya Laboratorium',
    description: 'Pembelian bahan kimia dan peralatan lab IPA',
    status: 'posted',
    referenceNumber: 'KAS-SMA-2026-0602',
    createdBy: 'Rizki Pratama',
  },
  {
    id: 'kas-8',
    schoolId: 'school-4',
    type: 'receipt',
    date: '2026-06-05',
    amount: 4750000,
    category: 'Penerimaan SPP',
    description: 'Rekap penerimaan SPP SMK Al-Hikmah Juni 2026',
    status: 'posted',
    referenceNumber: 'KAS-SMK-2026-0601',
    createdBy: 'Rizki Pratama',
  },
  {
    id: 'kas-9',
    schoolId: 'school-4',
    type: 'payment',
    date: '2026-06-14',
    amount: 5000000,
    category: 'Biaya Praktik',
    description: 'Pembelian komponen elektronik untuk praktik TKJ',
    status: 'draft',
    referenceNumber: 'KAS-SMK-2026-0602',
    createdBy: 'Rizki Pratama',
  },
  {
    id: 'kas-10',
    schoolId: 'school-5',
    type: 'receipt',
    date: '2026-06-06',
    amount: 3750000,
    category: 'Penerimaan SPP',
    description: 'Rekap penerimaan SPP MTs Al-Hikmah Juni 2026',
    status: 'posted',
    referenceNumber: 'KAS-MTS-2026-0601',
    createdBy: 'Dewi Kurniasih',
  },
  {
    id: 'kas-11',
    schoolId: 'school-1',
    type: 'receipt',
    date: '2026-06-15',
    amount: 1200000,
    category: 'Penerimaan Kegiatan',
    description: 'Pembayaran biaya ekstrakulikuler SD semester 1',
    status: 'posted',
    referenceNumber: 'KAS-SD-2026-0604',
    createdBy: 'Budi Santoso',
  },
  {
    id: 'kas-12',
    schoolId: 'school-2',
    type: 'payment',
    date: '2026-06-18',
    amount: 1800000,
    category: 'Perbaikan Gedung',
    description: 'Perbaikan atap aula SMP yang bocor',
    status: 'posted',
    referenceNumber: 'KAS-SMP-2026-0603',
    createdBy: 'Dewi Kurniasih',
  },
  {
    id: 'kas-13',
    schoolId: 'school-3',
    type: 'payment',
    date: '2026-06-20',
    amount: 850000,
    category: 'Biaya Internet',
    description: 'Pembayaran internet Telkom bulan Juni 2026',
    status: 'draft',
    referenceNumber: 'KAS-SMA-2026-0603',
    createdBy: 'Rizki Pratama',
  },
  {
    id: 'kas-14',
    schoolId: 'school-1',
    type: 'payment',
    date: '2026-05-15',
    amount: 600000,
    category: 'Biaya Air',
    description: 'Pembayaran PDAM bulan Mei 2026',
    status: 'reversed',
    referenceNumber: 'KAS-SD-2026-0510',
    createdBy: 'Budi Santoso',
  },
  {
    id: 'kas-15',
    schoolId: 'school-5',
    type: 'payment',
    date: '2026-06-22',
    amount: 2200000,
    category: 'Gaji Honorer',
    description: 'Pembayaran gaji guru honorer MTs Juni 2026',
    status: 'draft',
    referenceNumber: 'KAS-MTS-2026-0602',
    createdBy: 'Dewi Kurniasih',
  },
]
