import type { SavingsAccount, SavingsTransaction } from '@/types'

export const mockSavingsAccounts: SavingsAccount[] = [
  {
    id: 'tabungan-1',
    studentId: 'siswa-1',
    studentName: 'Muhammad Farhan Aditya',
    schoolId: 'school-1',
    balance: 850000,
    status: 'active',
  },
  {
    id: 'tabungan-2',
    studentId: 'siswa-2',
    studentName: 'Siti Aisyah Ramadhani',
    schoolId: 'school-1',
    balance: 1200000,
    status: 'active',
  },
  {
    id: 'tabungan-3',
    studentId: 'siswa-3',
    studentName: 'Rizky Dwi Putranto',
    schoolId: 'school-1',
    balance: 350000,
    status: 'active',
  },
  {
    id: 'tabungan-4',
    studentId: 'siswa-5',
    studentName: 'Aldi Firmansyah',
    schoolId: 'school-2',
    balance: 2100000,
    status: 'active',
  },
  {
    id: 'tabungan-5',
    studentId: 'siswa-6',
    studentName: 'Mega Lestari Putri',
    schoolId: 'school-2',
    balance: 750000,
    status: 'active',
  },
  {
    id: 'tabungan-6',
    studentId: 'siswa-7',
    studentName: 'Bagas Eko Prasetyo',
    schoolId: 'school-2',
    balance: 0,
    status: 'closed',
  },
  {
    id: 'tabungan-7',
    studentId: 'siswa-9',
    studentName: 'Dian Prabowo Utomo',
    schoolId: 'school-3',
    balance: 1550000,
    status: 'active',
  },
  {
    id: 'tabungan-8',
    studentId: 'siswa-14',
    studentName: 'Hasan Basri Muttaqin',
    schoolId: 'school-5',
    balance: 680000,
    status: 'active',
  },
  {
    id: 'tabungan-9',
    studentId: 'siswa-15',
    studentName: 'Zahra Aulia Rahma',
    schoolId: 'school-5',
    balance: 920000,
    status: 'active',
  },
  {
    id: 'tabungan-10',
    studentId: 'siswa-4',
    studentName: 'Nadia Putri Handayani',
    schoolId: 'school-1',
    balance: 450000,
    status: 'active',
  },
]

export const mockSavingsTransactions: SavingsTransaction[] = [
  {
    id: 'trx-tab-1',
    accountId: 'tabungan-1',
    type: 'deposit',
    amount: 200000,
    balanceAfter: 850000,
    date: '2026-06-10',
    notes: 'Setoran rutin Juni 2026',
    recordedBy: 'Budi Santoso',
  },
  {
    id: 'trx-tab-2',
    accountId: 'tabungan-1',
    type: 'deposit',
    amount: 200000,
    balanceAfter: 650000,
    date: '2026-05-10',
    notes: 'Setoran rutin Mei 2026',
    recordedBy: 'Budi Santoso',
  },
  {
    id: 'trx-tab-3',
    accountId: 'tabungan-2',
    type: 'deposit',
    amount: 300000,
    balanceAfter: 1200000,
    date: '2026-06-08',
    notes: 'Setoran tabungan wisuda',
    recordedBy: 'Budi Santoso',
  },
  {
    id: 'trx-tab-4',
    accountId: 'tabungan-2',
    type: 'withdrawal',
    amount: 500000,
    balanceAfter: 900000,
    date: '2026-04-15',
    notes: 'Penarikan untuk keperluan mendesak',
    recordedBy: 'Budi Santoso',
  },
  {
    id: 'trx-tab-5',
    accountId: 'tabungan-4',
    type: 'deposit',
    amount: 500000,
    balanceAfter: 2100000,
    date: '2026-06-12',
    notes: 'Setoran tabungan semester',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-6',
    accountId: 'tabungan-4',
    type: 'deposit',
    amount: 500000,
    balanceAfter: 1600000,
    date: '2026-05-12',
    notes: 'Setoran tabungan semester',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-7',
    accountId: 'tabungan-5',
    type: 'deposit',
    amount: 250000,
    balanceAfter: 750000,
    date: '2026-06-09',
    notes: 'Setoran rutin',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-8',
    accountId: 'tabungan-6',
    type: 'withdrawal',
    amount: 850000,
    balanceAfter: 0,
    date: '2026-05-30',
    notes: 'Penutupan rekening - siswa pindah sekolah',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-9',
    accountId: 'tabungan-7',
    type: 'deposit',
    amount: 400000,
    balanceAfter: 1550000,
    date: '2026-06-11',
    notes: 'Setoran tabungan bulanan',
    recordedBy: 'Rizki Pratama',
  },
  {
    id: 'trx-tab-10',
    accountId: 'tabungan-8',
    type: 'deposit',
    amount: 180000,
    balanceAfter: 680000,
    date: '2026-06-07',
    notes: 'Setoran rutin Juni 2026',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-11',
    accountId: 'tabungan-9',
    type: 'deposit',
    amount: 250000,
    balanceAfter: 920000,
    date: '2026-06-07',
    notes: 'Setoran rutin Juni 2026',
    recordedBy: 'Dewi Kurniasih',
  },
  {
    id: 'trx-tab-12',
    accountId: 'tabungan-10',
    type: 'deposit',
    amount: 150000,
    balanceAfter: 450000,
    date: '2026-06-06',
    notes: 'Setoran tabungan akhir tahun',
    recordedBy: 'Budi Santoso',
  },
]
