import type { Siswa } from '@/types'

export const mockSiswa: Siswa[] = [
  {
    id: 'siswa-1',
    name: 'Muhammad Farhan Aditya',
    nis: '2021001',
    kelas: 'IV A',
    jenjang: 'SD',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    status: 'aktif',
    parentName: 'Aditya Nugroho',
    parentPhone: '081234567801',
    vaNumber: 'VA-SD100001',
  },
  {
    id: 'siswa-2',
    name: 'Siti Aisyah Ramadhani',
    nis: '2021002',
    kelas: 'IV A',
    jenjang: 'SD',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    status: 'aktif',
    parentName: 'Ramadhani Susilo',
    parentPhone: '081234567802',
    vaNumber: 'VA-SD100002',
  },
  {
    id: 'siswa-3',
    name: 'Rizky Dwi Putranto',
    nis: '2020015',
    kelas: 'V B',
    jenjang: 'SD',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    status: 'aktif',
    parentName: 'Dwi Putranto',
    parentPhone: '081234567803',
    vaNumber: 'VA-SD100003',
  },
  {
    id: 'siswa-4',
    name: 'Nadia Putri Handayani',
    nis: '2019030',
    kelas: 'VI A',
    jenjang: 'SD',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    status: 'aktif',
    parentName: 'Handayani Wibowo',
    parentPhone: '081234567804',
    vaNumber: 'VA-SD100004',
  },
  {
    id: 'siswa-5',
    name: 'Aldi Firmansyah',
    nis: '2022101',
    kelas: 'VII A',
    jenjang: 'SMP',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    status: 'aktif',
    parentName: 'Firmansyah Hakim',
    parentPhone: '081234567805',
    vaNumber: 'VA-SMP200001',
  },
  {
    id: 'siswa-6',
    name: 'Mega Lestari Putri',
    nis: '2022102',
    kelas: 'VII B',
    jenjang: 'SMP',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    status: 'aktif',
    parentName: 'Lestari Hariyanto',
    parentPhone: '081234567806',
    vaNumber: 'VA-SMP200002',
  },
  {
    id: 'siswa-7',
    name: 'Bagas Eko Prasetyo',
    nis: '2021110',
    kelas: 'VIII A',
    jenjang: 'SMP',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    status: 'aktif',
    parentName: 'Eko Prasetyo',
    parentPhone: '081234567807',
    vaNumber: 'VA-SMP200003',
  },
  {
    id: 'siswa-8',
    name: 'Anisa Nur Fadilah',
    nis: '2020120',
    kelas: 'IX B',
    jenjang: 'SMP',
    schoolId: 'school-2',
    schoolName: 'SMP Al-Hikmah',
    status: 'aktif',
    parentName: 'Fadilah Rohmat',
    parentPhone: '081234567808',
    vaNumber: 'VA-SMP200004',
  },
  {
    id: 'siswa-9',
    name: 'Dian Prabowo Utomo',
    nis: '2023201',
    kelas: 'X IPA 1',
    jenjang: 'SMA',
    schoolId: 'school-3',
    schoolName: 'SMA Al-Hikmah',
    status: 'aktif',
    parentName: 'Prabowo Utomo',
    parentPhone: '081234567809',
    vaNumber: 'VA-SMA300001',
  },
  {
    id: 'siswa-10',
    name: 'Fitriani Wahyuningsih',
    nis: '2023202',
    kelas: 'X IPS 1',
    jenjang: 'SMA',
    schoolId: 'school-3',
    schoolName: 'SMA Al-Hikmah',
    status: 'aktif',
    parentName: 'Wahyuningsih Santoso',
    parentPhone: '081234567810',
    vaNumber: 'VA-SMA300002',
  },
  {
    id: 'siswa-11',
    name: 'Irfan Maulana Akbar',
    nis: '2022210',
    kelas: 'XI IPA 2',
    jenjang: 'SMA',
    schoolId: 'school-3',
    schoolName: 'SMA Al-Hikmah',
    status: 'aktif',
    parentName: 'Maulana Akbar',
    parentPhone: '081234567811',
    vaNumber: 'VA-SMA300003',
  },
  {
    id: 'siswa-12',
    name: 'Yusuf Habibie Rachman',
    nis: '2023301',
    kelas: 'X TKJ 1',
    jenjang: 'SMK',
    schoolId: 'school-4',
    schoolName: 'SMK Al-Hikmah',
    status: 'aktif',
    parentName: 'Habibie Rachman',
    parentPhone: '081234567812',
    vaNumber: 'VA-SMK400001',
  },
  {
    id: 'siswa-13',
    name: 'Rina Permata Sari',
    nis: '2023302',
    kelas: 'X AKL 1',
    jenjang: 'SMK',
    schoolId: 'school-4',
    schoolName: 'SMK Al-Hikmah',
    status: 'aktif',
    parentName: 'Permata Sari Hasan',
    parentPhone: '081234567813',
    vaNumber: 'VA-SMK400002',
  },
  {
    id: 'siswa-14',
    name: 'Hasan Basri Muttaqin',
    nis: '2022401',
    kelas: 'VII A',
    jenjang: 'MTs',
    schoolId: 'school-5',
    schoolName: 'MTs Al-Hikmah',
    status: 'aktif',
    parentName: 'Basri Muttaqin',
    parentPhone: '081234567814',
    vaNumber: 'VA-MTS500001',
  },
  {
    id: 'siswa-15',
    name: 'Zahra Aulia Rahma',
    nis: '2022402',
    kelas: 'VII B',
    jenjang: 'MTs',
    schoolId: 'school-5',
    schoolName: 'MTs Al-Hikmah',
    status: 'aktif',
    parentName: 'Aulia Rahma Yusuf',
    parentPhone: '081234567815',
    vaNumber: 'VA-MTS500002',
  },
  {
    id: 'siswa-16',
    name: 'Taufiq Hidayatullah',
    nis: '2021035',
    kelas: 'VI B',
    jenjang: 'SD',
    schoolId: 'school-1',
    schoolName: 'SD Al-Hikmah',
    status: 'lulus',
    parentName: 'Hidayatullah Firdaus',
    parentPhone: '081234567816',
    vaNumber: 'VA-SD100016',
  },
]
